# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

target 'socket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'VPSocketIO', '~> 1.0.5' # Or latest version
  pod 'Socket.IO-Client-Swift', '~> 13.2.1'

end


